version: '3'
services:
  dbt:
    build:
      context: .
      target: dbt-all
    volumes:
      - .:/usr/app/dbt

  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
